### ISSUE TITLE
Support custom ports

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#146]
In addition to existing port selection, we need to add a custom input field that accepts a single port number within the supported ranges. Supported port ranges are fetched from the servers.json API, separately for OpenVPN and WireGuard.

**Comment by gorkapernas** [comment]
**Note:**
I'm not able to install the latest apk on an Android 8 tablet. 
It seems like for this ticket some dependencies were upgraded as well as the Kotlin version, so this could be cause of the issue on old Android versions. Needs further investigation.

**Comment by gorkapernas** [comment]
Verified on 2.9.0, @jurajhilje please see my comments below.

- It is possible to add non numeric characters to the port input field, it is suggested to restrict the input to numbers only.
- Tapping on the Enter key ↵, increases the input box, the enter key should either validate the input or the key action should be disable, so nothing happens when tapping on it.
- It is possible to add multiple times the same port, please note that in the iOS and desktop apps this is restricted, so it is suggested to add a validation in order to prevent the user from adding the same port more than once. Tested with OpenVPN and WireGuard, UDP and TCP.
- In the iOS and desktop apps when adding a new port, this will appear on both protocols, i.e. if I add a new port to OpenVPN (UDP), this same port will be available for WireGuard and vice versa. This is not the case in the Android app, the new port is only saved for the active protocol.
- Again, in the iOS and desktop apps, when creating a new port, this is automatically selected by the apps, however in the Android app, the user needs to select the new port manually after creating it.

**Comment by gorkapernas** [comment]
Verified in the latest beta, @jurajhilje it seems that the following issue is not fixed.

>It is possible to add multiple times the same port, please note that in the iOS and desktop apps this is restricted, so it is suggested to add a validation in order to prevent the user from adding the same port more than once. Tested with OpenVPN and WireGuard, UDP and TCP.

Tested on two different devices, Android 12 and 13.

See screenshot for further details.
![duplicate ports](https://github.com/ivpn/android-app/assets/16647612/94205d2b-77f6-4c27-94fe-10bcdab17f53)

**Comment by gorkapernas** [comment]
Verified in the latest beta, the remaining issue has been fixed, it is no longer possible to create duplicate ports on any of the existing protocols. 
No more issues have been found, the custom ports feature looks good to go.
