### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by rakleed** [ivpn/android-app#152]
# Feature request

## Description

Android TV lacks a convenient way to connect to IVPN.

## Describe the solution you'd like

Adapt your Android app for Android TV and submit it on Google Play.

**Comment by jurajhilje** [comment]
This feature is not planned at the moment.

**Comment by candroid-man** [comment]
Look at it this way. ProtonVPN and Mullvad are both on Android TV, and I'm no programmer but this seems like a really easy thing to do. Just add remote controls to the Android app and call it a day. Every time I reboot my Android TV it disconnects from the VPN, and in order to use your app I had to sideload it meaning I have to grab a mouse, plug it in to my Android TV, and then hit the connect button.
