### ISSUE TITLE
Use same favorite server for OpenVPN and WireGuard

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#199]
## Description:

Currently, each protocol can have a different favorite server configuration. The favorite server configuration should be the same for all protocols.

**Comment by jurajhilje** [comment]
@gorkapernas This is similar to the issue in https://github.com/ivpn/android-app/issues/59#issuecomment-1481533588

**Comment by gorkapernas** [comment]
@jurajhilje there is a problem if we keep the favorite servers separated for each protocol after the IVPN version update, if we do so, when adding a favorite server which is already in the other protocol, this server will be displayed twice in the favorite list of the other protocol.

**Steps:**
1. Install v2.8.5.
2. Login.
3. Add two favorite servers for WireGuard (e.g. Paris, Brussels), and two other different servers for OpenVPN (Milan, Amsterdam).
4. Update IVPN tp v2.8.6.
5. Observe that the favorite servers configuration is still different for each protocol.
6. With WireGuard, add Milan and Amsterdam as favorite.
7. Select OpenVPN and open the favorite servers list.
8. Observe that Milan and Amsterdam are displayed twice since it was already selected as favorite for OpenVPN before the update.

**Screenshot:**
![favorite servers_android](https://user-images.githubusercontent.com/16647612/228815116-43704825-0f30-4267-82e1-f72a1665ccae.png)

**Comment by gorkapernas** [comment]
Verified fixed in the latest apk v2.8.6, tested on Samsung Galaxy S10 Android 12, there are no more duplicate servers after performing the steps described on https://github.com/ivpn/android-app/issues/199#issuecomment-1490098951

Currently the app keeps the same old favorite server configuration after the update (even if it's different between protocols), but once the app is updated to the new version (or new installation), the app adds the same favorite servers to both protocols.
