### ISSUE TITLE
AntiTracker Plus

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#248]

**Comment by gorkapernas** [comment]
There a few changes that need to be done:

- We need to update the Android app behavior according to the following requirement:
`Enable user to access AntiTracker settings from the main app screen`
- We need to add a missing text which was present in previous build and contained the link to https://www.ivpn.net/antitracker

**UI issue:**
- When highlighting 4 of the block lists (touch & hold) together and lifting them, the app redirects you to the main screen and all the buttons becomes locked such as profile, settings, protocol selection... this is not an issue on iOS, only one list at a time can be highlighted.
See video below for further details.

https://github.com/ivpn/android-app/assets/16647612/b0926434-984d-4c30-afcb-a7bb902ac8b8

**Comment by gorkapernas** [comment]
@jurajhilje the issue with multi touch selection is fixed, also the missing text has been added correctly. Unfortunately there is a problem with accessing AntiTracker from the sliding panel. 

**Issue:**
Current Android app logic doesn't allow you to access some menus (including AntiTracker Settings) if you are connected to the VPN, however this is not the case if accessing AntiTracker from the main screen. This is a problem because changing the AntiTracker configuration while connected doesn't have any effect unless the user reconnects manually.
It is suggested to make inaccessible the AntiTracker Settings from the sliding panel when the VPN is connected and display the existing message `To use AntiTracker, please disconnect first` in order to keep consistency across the app, or prompt the user to reconnect when any of the AntiTracker settings are changed while connected (current iOS implementation).
The last solution would be the best, but it should also be done with all the other settings (a task for the future?).

**Additional observation:**
I tried to install the apk in an Android 5.1 device, but it doesn't seem to be compatible, I get the following error -> `There was a problem parsing the package`.

**Suggestion:**
Would it be possible to reduce slightly the tapping area for accessing AntiTracker from the sliding panel? Sometimes when I try to toggle on/off the button, I access the AntiTracker settings instead. It could be device related or my sausage fingers 😄 
We have the same implementation on iOS, but I find it easier to toggle on/off the button without accessing the AntiTracker settings.

**Comment by gorkapernas** [comment]
Issues reported previously have been fixed.

However, new changes need to be implemented in the default AntiTracker block list:

- User is logged in or has stored AntiTracker preference, updates from old to new app version -> default AntiTracker list is OISD Big list
- User is not logged in and has no stored AntiTracker preferences, updates from old to new app version -> default AntiTracker list is Basic
- User installs the new app version for the first time -> default AntiTracker list is Basic

**Comment by gorkapernas** [comment]
Tested the latest beta on different devices and Android versions without observing anymore issues, this is good to go.
