### ISSUE TITLE
Upgrade WireGuard

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#281]
## Description

Upgrade WireGuard to the latest version:
https://github.com/WireGuard/wireguard-android
https://central.sonatype.com/artifact/com.wireguard.android/tunnel/versions

**Comment by gorkapernas** [comment]
@jurajhilje tested Wireguard on 2.10.5 and I haven't noticed any particular issues which might have been caused by the WireGuard version upgrade, therefore, I'll move this ticket to deployable.
However, I still experience this issue https://github.com/ivpn/android-app/issues/128, should we look into it before the release? It shouldn't be a blocker since it's not a regression issue.
