### ISSUE TITLE
Improve UX for pending payments

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#316]
## Description

IVPN Android app currently has support for pending payments, however the UX should be improved.

Current result:
- User initiates a payment with `PENDING` status
- App displays an alert about not completing the payment and prompt to restart the app
- App restart initiates validation for all non completed payments and completes the payment

Expected result:
- User initiates a payment with `PENDING` status
- App displays an alert about pending payment
- App should complete the payment as soon as status changes to `PURCHASED`, without need to restart the app

## QA Notes

How to test pending purchases:
https://developer.android.com/google/play/billing/test#pending-purchases

**Comment by jurajhilje** [comment]
@gorkapernas This is available for QA.

**Comment by gorkapernas** [comment]
Verified on v2.10.8, I confirm the expected result described in the ticket.
When a payment takes longer than expected, i.e. payment is on Pending status, the app displays the following message:

![Image 2024-02-15 at 12 02 42 PM](https://github.com/ivpn/android-app/assets/16647612/e87ccae3-bd23-441e-b94d-c020287421c8)

Then the payment is validated without the user having to restart the application. 

However, the user is not redirected to the application after the payment is validated, the app still remains in the plan selection screen, so in the end, the app must restarted in order to access the service (issue reproducible when creating a new account). 
@jurajhilje would it be possible to improve this behaviour?

**Expected result:**
- When a pending payment is validated, the user should be redirected to the home screen in order to be able to use the VPN service immediately.

**Comment by jurajhilje** [comment]
@gorkapernas 
New APK is available.

Expected result is:
- Generate account ID
- Make intial purchase with delayed payment
- "Pending payment" alert is displayed
- When alert is dismissed, app navigates back to the main screen
- When pending payment is processed, app displays "Processing payment" and then "Creating session" dialogs

Se, there should be no need to restart the app in order to process the pending payment, activate service and create session.

**Comment by gorkapernas** [comment]
Verified on the latest beta, the last issue reported has been fixed, the app behaves as described here:
https://github.com/ivpn/android-app/issues/316#issuecomment-1957448313

Currently there is no need to restart the application to start using the service after the pending payment is validated. Tested initial payment and also renewals. This looks good to go.
