### ISSUE TITLE
Implement dynamic connection info

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#86]
Replace text 'Connect to' with:

If multi-hop is disabled:

a) If disconnected and (server has been manually selected OR random enabled): "Selected server".
b) If disconnected and 'fastest available' server is selected: "Fastest available server" and show server details i.e. Flag, location etc. When background latency check is run update server.
c) If connected: "Traffic is routed via server".

If multi-hop is enabled:

a) If disconnected then entry: "Entry server is" and exit: "Exit server is"
b) If connected then entry: "Traffic is routed via entry server" and exit: Traffic is routed via exit server"

**Comment by gorkapernas** [comment]
Verified on version 2.7.0, Samsung Galaxy S10 Android 11, Huawei MediaTab Android 8.1.

@AlexKorvin I believe the following point hasn't been implemented.
>If multi-hop is disabled:
b) If disconnected and 'fastest available' server is selected: "Fastest available server" and show server details i.e. Flag, location etc. When background latency check is run update server.

From what I understand, when the fastest server is selected, the app should display the actual server (location + flag) instead of the label "Fastest server" and the old "Connect to" label should replaced with "Fastest available server" . Can you confirm this @jurajhilje? This is how it looks right now 👇 
![fastest server_Android](https://user-images.githubusercontent.com/16647612/131363168-7f3fb233-024d-4c22-908a-6202ec45c006.png)

**Comment by jurajhilje** [comment]
@gorkapernas Yes correct. The current iOS implementation is very similar to this requirement, check out the screenshot:
cc: @AlexKorvin 

<img src="https://user-images.githubusercontent.com/3176222/131460145-2de787dd-0f3d-40fe-a1f7-0b918105231c.PNG" alt="iOS app" width="400"/>

**Comment by gorkapernas** [comment]
@jurajhilje @AlexKorvin again, there is an inconsistency between clients.
- the green badge "Fastest" is shown on Android and iOS, but not on Desktop, however on Android the badge disappears after connecting.
- the text "Fastest available server" is shown for iOS and Desktop, but not for Android which shows "Selected server"

See screenshots below.

**Android:**
![android_fastest](https://user-images.githubusercontent.com/16647612/134342670-abee50d5-f226-483b-8a35-16be35f3bcbe.png)

**macOS:**
![macOS_fastest](https://user-images.githubusercontent.com/16647612/134342688-b4f111db-776b-471c-9bb4-70d807090e9a.png)

**iOS:**
![iOS_fastest](https://user-images.githubusercontent.com/16647612/134342723-6271e1fb-cd9e-46dd-8b40-7ae8df50be19.png)

Should we unify the implementation? 

 //Cc @stenya

**Comment by jurajhilje** [comment]
I think that Desktop app is correct, so we should remove this green "FASTEST" label in the mobile apps.

**Comment by gorkapernas** [comment]
@jurajhilje yeah, the label "Fastest" seems redundant since we have the text ""Fastest available server" pointing this out when disconnected, however, this label is also used on iOS when connected which confirms that the user is connected to the fastest server, so this is good on the other hand.
But yeah, agreed, probably the desktop client is the best approach.

//Cc @AlexKorvin ^^

**Comment by AlexKorvin** [comment]
Let's wait for Nick final decision. It's not a big deal to change the label.

**Comment by gorkapernas** [comment]
@AlexKorvin I noticed that the fastest server green label has been removed on the latest beeta, however, there are still an inconsistency with the other two clients. 
See point following point from my previous comment
>the text "Fastest available server" is shown for iOS and Desktop, but not for Android which shows "Selected server"

Please see screenshot below to compare clients:
![fastest server_text](https://user-images.githubusercontent.com/16647612/137500713-cb8a5b3f-8e03-4157-a1e4-3db8ffc28021.png)
